
// This file was auto-generated by ML.NET Model Builder. 

using SentimentConsole;

// Create single instance of sample data from first line of dataset for model input
SentimentModel1.ModelInput sampleData = new SentimentModel1.ModelInput()
{
    Text = @"mükemmel bir ürün için teşekkürler.",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


Console.WriteLine($"Label: {true}");
Console.WriteLine($"Text: {@"mükemmel bir ürün için teşekkürler."}");


var predictionResult = SentimentModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.PredictedLabel}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

